### ISSUE TITLE
Non-effective Disconnect

### ISSUE THREAD

**Issue by twittwer** [thenativeweb/json-lines-client#2]
### Situation:
I'm using the json-lines connection for a channel subscription and the user should be able to change the subscribed channels.
Therefore I try to disconnect the stream connection and open a new one with the new channel subscriptions.
> If you want to cancel receiving a stream from the client, call the server's disconnect function. `server.disconnect();`   - [README](https://github.com/thenativeweb/json-lines-client/blob/master/README.md)
```
var serverConnection = null;

function connect ( channels ) {
  if ( serverConnection ) {
    serverConnection.disconnect();
  }

  client( {
    protocol: 'http',
    host: 'example.com',
    port: 4242,
    path: '/subscribe',
    body: channels
  }, server => {

    serverConnection = server;

    // do some data & error handling
  } );
}
```

### Problem
The call of `server.disconnect()` doesn't have any effect on the server-side. That way the connection is closed on client-side but the server doesn't recognize it and still tries to send data.
I tried several listeners (disconnect, abort, end, destroy, close) on the request, response, response.socket and client object on in the backend, but none of them was executed.
FYI: The client-side is `req.destroy` is executed.
```
disconnect() {
  if ( res && res.socket && res.socket.end ) {
    return res.socket.end();
  }
  if ( req && req.destroy ) {
    return req.destroy(); // <-- executed
  }
  // We don't know how to close the connection, but this situation should
  // definitely be avoided.
}
```
https://github.com/thenativeweb/json-lines-client/blob/master/lib/jsonLinesClient.js#L51

### Thoughts
After looking into the internal destroy function and the referenced issue, I'm not sure if it's possible to close the connection from client side. 😕 
```
ClientRequest.prototype.abort = ClientRequest.prototype.destroy = function () {
	var self = this
	self._destroyed = true
	if (self._response)
		self._response._destroyed = true
	if (self._xhr)
		self._xhr.abort()
	// Currently, there isn't a way to truly abort a fetch.
	// If you like bikeshedding, see https://github.com/whatwg/fetch/issues/27
}
```
https://github.com/whatwg/fetch/issues/27

I would be deeply grateful for any idea. 🙂 
Otherwise, if it's really impossible the documentation of disconnect could maybe be removed or append by a hint to this behavior.

**Comment by twittwer** [comment]
FYI: To solve the problem of IE support I started an module ([json-lines-xhr-client](https://github.com/twittwer/json-lines-xhr-client)) using plain XMLHttpRequests to work with your [json-lines](https://github.com/thenativeweb/json-lines) backend module.
It supports IE and enables also client-side disconnects.

**Comment by goloroden** [comment]
Maybe we can merge this at some point in time with this one?

**Comment by twittwer** [comment]
Of course
I already thought of forking, but there were to many differences at first and the tests were failing right after cloning, so I started from scratch. But we can have a look at consolidating after my currently ongoing bachelor thesis is finished.

**Comment by goloroden** [comment]
This would be great 👍

**Comment by twittwer** [comment]
@goloroden @mattwagl 
Like I announced at the meetup last week, I have published the modules for the different building blocks of the pub/sub pipeline. Also I added the [prototype setup](https://github.com/twittwer/bvd-intercom) as a little playground ;)
For the json-lines-client module the repos [jl-client](https://github.com/twittwer/jl-client) & [jl-receiver](https://github.com/twittwer/jl-receiver) could be interesting.

**Comment by goloroden** [comment]
Hi @twittwer!

Thanks for getting back to this.
I would like to add @mattwagl to this discussion, but this week he's out of office. We will get  back to you next week!

**Comment by mattwagl** [comment]
I'm really sorry it took me so long to respond but I was pretty busy. I also needed to have a look at the repos you've mentionend. First of all, thanks for sharing them and for reaching out! I'll first try recap what I think the different modules do: `jl-client` is the low-level module that wraps the XHR object that you created because `server.disconnect` doesn't actually disconnect. I also created a little test case to verify this and it seems you're right – so thanks for pointing that out. The `server.disconnect` function doesn't have an effect when being run inside the browser. This flakiness when it comes to using the `http/https` stream based APIs in the browser with xhr under the hood was actually one of the reasons why we've been moving to Websockets for the `wolkenkit-client-js` module as the default transport layer for the streaming of events. 

`jl-receiver` is a higher-level module that uses `jl-client` but adds disconnect handling on top of it. I didn't quite get how the reconnection handover is accomplished but it basically sounds interesting because reconnect handling is something that would be very helpful.

So I'm not sure how to continue from here. Maybe a few questions might help: Were you able to verify that it works across different browsers? In other words how battle-tested are these modules? And finally are you interested in merging/maintaining this kind of functionality our would you rather hand it over as you won't be able to keep working on it?

**Comment by goloroden** [comment]
Closed due to inactivity, and as we won't maintain this module any more in the future.
